window.LESSON_DATA = {
  meta: {
    id: 'bt-control',
    title: '控制流',
    chapter: 'basics-test',
    index: 3,
    filename: 'control-flow.c',
    keyPoints: ['条件分支', '循环结构', '跳转控制']
  },
  codeLines: [
    { num: 1, tokens: [{ type: 'pp', text: '#include' }, { type: 'ws', text: ' ' }, { type: 'str', text: '<stdio.h>' }] },
    { num: 2, tokens: [{ type: 'ws', text: ' ' }] },
    { num: 3, tokens: [{ type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'fn', text: 'main' }, { type: 'punc', text: '()' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 4, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'score' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'num', text: '85' }, { type: 'punc', text: ';' }] },
    { num: 5, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'char' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'grade' }, { type: 'punc', text: ';' }] },
    { num: 6, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'if' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '(' }, { type: 'id', text: 'score' }, { type: 'ws', text: ' ' }, { type: 'op', text: '>=' }, { type: 'ws', text: ' ' }, { type: 'num', text: '90' }, { type: 'punc', text: ')' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 7, tokens: [{ type: 'ws', text: '        ' }, { type: 'id', text: 'grade' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'str', text: "'A'" }, { type: 'punc', text: ';' }] },
    { num: 8, tokens: [{ type: 'ws', text: '    ' }, { type: 'punc', text: '}' }, { type: 'ws', text: ' ' }, { type: 'kw', text: 'else' }, { type: 'ws', text: ' ' }, { type: 'kw', text: 'if' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '(' }, { type: 'id', text: 'score' }, { type: 'ws', text: ' ' }, { type: 'op', text: '>=' }, { type: 'ws', text: ' ' }, { type: 'num', text: '80' }, { type: 'punc', text: ')' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 9, tokens: [{ type: 'ws', text: '        ' }, { type: 'id', text: 'grade' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'str', text: "'B'" }, { type: 'punc', text: ';' }] },
    { num: 10, tokens: [{ type: 'ws', text: '    ' }, { type: 'punc', text: '}' }, { type: 'ws', text: ' ' }, { type: 'kw', text: 'else' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 11, tokens: [{ type: 'ws', text: '        ' }, { type: 'id', text: 'grade' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'str', text: "'C'" }, { type: 'punc', text: ';' }] },
    { num: 12, tokens: [{ type: 'ws', text: '    ' }, { type: 'punc', text: '}' }] },
    { num: 13, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'sum' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ';' }] },
    { num: 14, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'for' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '(' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ';' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' }, { type: 'ws', text: ' ' }, { type: 'op', text: '<' }, { type: 'ws', text: ' ' }, { type: 'num', text: '5' }, { type: 'punc', text: ';' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' }, { type: 'op', text: '++' }, { type: 'punc', text: ')' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 15, tokens: [{ type: 'ws', text: '        ' }, { type: 'id', text: 'sum' }, { type: 'ws', text: ' ' }, { type: 'op', text: '+=' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' }, { type: 'punc', text: ';' }] },
    { num: 16, tokens: [{ type: 'ws', text: '    ' }, { type: 'punc', text: '}' }] },
    { num: 17, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'count' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ';' }] },
    { num: 18, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'while' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '(' }, { type: 'id', text: 'count' }, { type: 'ws', text: ' ' }, { type: 'op', text: '<' }, { type: 'ws', text: ' ' }, { type: 'num', text: '3' }, { type: 'punc', text: ')' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 19, tokens: [{ type: 'ws', text: '        ' }, { type: 'id', text: 'count' }, { type: 'op', text: '++' }, { type: 'punc', text: ';' }] },
    { num: 20, tokens: [{ type: 'ws', text: '    ' }, { type: 'punc', text: '}' }] },
    { num: 21, tokens: [{ type: 'ws', text: '    ' }, { type: 'fn', text: 'printf' }, { type: 'punc', text: '(' }, { type: 'str', text: '"grade=%c, sum=%d, count=%d\\n"' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'grade' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'sum' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'count' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 22, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'return' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ';' }] },
    { num: 23, tokens: [{ type: 'punc', text: '}' }] }
  ],
  varConfig: [
    { key: 'score', name: 'score', type: 'int', addr: '0x7ffc00', glowColor: 'rgba(34,197,94,0.35)', accentCls: 'text-green-400', badgeCls: 'text-green-400 border-green-500/30 bg-green-500/12', appearStep: 1 },
    { key: 'grade', name: 'grade', type: 'char', addr: '0x7ffc04', glowColor: 'rgba(59,130,246,0.35)', accentCls: 'text-blue-400', badgeCls: 'text-blue-400 border-blue-500/30 bg-blue-500/12', appearStep: 2 },
    { key: 'sum', name: 'sum', type: 'int', addr: '0x7ffc08', glowColor: 'rgba(249,115,22,0.35)', accentCls: 'text-orange-400', badgeCls: 'text-orange-400 border-orange-500/30 bg-orange-500/12', appearStep: 3 },
    { key: 'i', name: 'i', type: 'int', addr: '0x7ffc0c', glowColor: 'rgba(168,85,247,0.35)', accentCls: 'text-purple-400', badgeCls: 'text-purple-400 border-purple-500/30 bg-purple-500/12', appearStep: 4 },
    { key: 'count', name: 'count', type: 'int', addr: '0x7ffc10', glowColor: 'rgba(236,72,153,0.35)', accentCls: 'text-pink-400', badgeCls: 'text-pink-400 border-pink-500/30 bg-pink-500/12', appearStep: 6 }
  ],
  scenes: [
    { step: 0, line: -1, executedLines: [], vars: {}, highlightVar: null, isDanger: false, output: [], explanation: { icon: 'rocket', text: '点击播放，开始学习控制流', color: 'blue', actor: null, detail: null }, prediction: null, misconception: null, actor: null, target: null, timing: null },
    { step: 1, line: 4, executedLines: [2, 3], vars: { score: 85 }, highlightVar: 'score', isDanger: false, output: [], explanation: { icon: 'memory', text: '声明 int 变量 score = 85', color: 'yellow', actor: 'CPU', detail: 'score 变量存储在栈上，占用 4 字节。初始值 85 被写入内存地址 0x7ffc00。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:score', timing: 'main-loop' },
    { step: 2, line: 5, executedLines: [2, 3, 4], vars: { score: 85, grade: '\u0000' }, highlightVar: 'grade', isDanger: false, output: [], explanation: { icon: 'memory', text: '声明 char 变量 grade，未初始化', color: 'blue', actor: 'CPU', detail: 'grade 是 char 类型占 1 字节。未初始化时其值是栈上残留数据 (不确定)，不一定为 0。应始终初始化变量。' }, prediction: { question: '未初始化的局部变量 grade 的值是什么？', options: ['0', '不确定 (栈上残留数据)', 'NULL'], answer: 1 }, misconception: { title: '未初始化局部变量不等于 0', text: '全局变量和 static 变量会自动初始化为 0，但栈上的局部变量不会。未初始化的局部变量值是之前栈帧残留的数据，是随机的。' }, actor: 'CPU', target: 'var:grade', timing: 'main-loop' },
    { step: 3, line: 6, executedLines: [2, 3, 4, 5], vars: { score: 85, grade: '\u0000' }, highlightVar: null, isDanger: false, output: [], explanation: { icon: 'target', text: '判断条件 score>=90，即 85>=90 为假', color: 'orange', actor: 'CPU', detail: 'CPU 执行 CMP 指令比较两个值，设置标志寄存器。85<90，所以条件为假，跳转到 else 分支执行。' }, prediction: null, misconception: null, actor: 'CPU', target: 'control-flow', timing: 'condition-check' },
    { step: 4, line: 8, executedLines: [2, 3, 4, 5, 6, 7], vars: { score: 85, grade: '\u0000' }, highlightVar: null, isDanger: false, output: [], explanation: { icon: 'target', text: '判断条件 score>=80，即 85>=80 为真', color: 'orange', actor: 'CPU', detail: '进入 else-if 分支，再次判断 85>=80 为真，执行对应的代码块。' }, prediction: null, misconception: null, actor: 'CPU', target: 'control-flow', timing: 'condition-check' },
    { step: 5, line: 9, executedLines: [2, 3, 4, 5, 6, 7, 8], vars: { score: 85, grade: 'B' }, highlightVar: 'grade', isDanger: false, output: [], explanation: { icon: 'check', text: '执行 grade = \'B\'，grade 现在是字符\'B\'(ASCII 66)', color: 'green', actor: 'CPU', detail: '字符常量\'B\'的 ASCII 码是 66。CPU 将 66 写入 grade 变量的内存地址。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:grade', timing: 'main-loop' },
    { step: 6, line: 13, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], vars: { score: 85, grade: 'B', sum: 0 }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'memory', text: '声明 int 变量 sum = 0，用于累加', color: 'yellow', actor: 'CPU', detail: 'sum 初始化为 0，这是累加器常见模式。如果不初始化，累加结果会错误。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:sum', timing: 'main-loop' },
    { step: 7, line: 14, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], vars: { score: 85, grade: 'B', sum: 0, i: 0 }, highlightVar: 'i', isDanger: false, output: [], explanation: { icon: 'memory', text: 'for 循环初始化 i=0', color: 'blue', actor: 'CPU', detail: 'for 循环三要素：初始化 (i=0)、条件 (i<5)、迭代 (i++)。初始化只在循环开始时执行一次。' }, prediction: { question: 'for 循环执行几次？', options: ['4 次 (0,1,2,3)', '5 次 (0,1,2,3,4)', '6 次 (0,1,2,3,4,5)'], answer: 1 }, misconception: null, actor: 'CPU', target: 'var:i', timing: 'loop-init' },
    { step: 8, line: 15, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], vars: { score: 85, grade: 'B', sum: 0, i: 0 }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'bolt', text: '第一次循环：sum += 0，sum 仍为 0', color: 'green', actor: 'CPU', detail: 'i=0 时，sum = sum + i = 0 + 0 = 0。累加 0 不改变结果。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:sum', timing: 'loop-body' },
    { step: 9, line: 14, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], vars: { score: 85, grade: 'B', sum: 0, i: 1 }, highlightVar: 'i', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'i++ 后 i=1，判断 i<5 为真，继续循环', color: 'purple', actor: 'CPU', detail: '循环迭代：i 自增为 1，然后判断条件 1<5 为真，进入第二次循环。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:i', timing: 'loop-iter' },
    { step: 10, line: 15, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14], vars: { score: 85, grade: 'B', sum: 1, i: 1 }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'bolt', text: '第二次循环：sum += 1，sum 变为 1', color: 'green', actor: 'CPU', detail: 'sum = sum + i = 0 + 1 = 1。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:sum', timing: 'loop-body' },
    { step: 11, line: 14, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 15], vars: { score: 85, grade: 'B', sum: 1, i: 2 }, highlightVar: 'i', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'i++ 后 i=2，继续循环', color: 'purple', actor: 'CPU', detail: 'i 自增为 2，判断 2<5 为真。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:i', timing: 'loop-iter' },
    { step: 12, line: 15, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 15, 14], vars: { score: 85, grade: 'B', sum: 3, i: 2 }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'bolt', text: '第三次循环：sum += 2，sum 变为 3', color: 'green', actor: 'CPU', detail: 'sum = sum + i = 1 + 2 = 3。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:sum', timing: 'loop-body' },
    { step: 13, line: 14, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 15, 14, 15], vars: { score: 85, grade: 'B', sum: 3, i: 3 }, highlightVar: 'i', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'i++ 后 i=3，继续循环', color: 'purple', actor: 'CPU', detail: 'i 自增为 3，判断 3<5 为真。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:i', timing: 'loop-iter' },
    { step: 14, line: 15, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 15, 14, 15, 14], vars: { score: 85, grade: 'B', sum: 6, i: 3 }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'bolt', text: '第四次循环：sum += 3，sum 变为 6', color: 'green', actor: 'CPU', detail: 'sum = sum + i = 3 + 3 = 6。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:sum', timing: 'loop-body' },
    { step: 15, line: 14, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 15, 14, 15, 14, 15], vars: { score: 85, grade: 'B', sum: 6, i: 4 }, highlightVar: 'i', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'i++ 后 i=4，继续循环', color: 'purple', actor: 'CPU', detail: 'i 自增为 4，判断 4<5 为真，这是最后一次循环。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:i', timing: 'loop-iter' },
    { step: 16, line: 15, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 15, 14, 15, 14, 15, 14], vars: { score: 85, grade: 'B', sum: 10, i: 4 }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'bolt', text: '第五次循环：sum += 4，sum 变为 10', color: 'green', actor: 'CPU', detail: 'sum = sum + i = 6 + 4 = 10。0+1+2+3+4=10。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:sum', timing: 'loop-body' },
    { step: 17, line: 16, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 15, 14, 15, 14, 15, 14, 15], vars: { score: 85, grade: 'B', sum: 10, i: 4 }, highlightVar: null, isDanger: false, output: [], explanation: { icon: 'check', text: 'i++ 后 i=5，判断 i<5 为假，退出循环', color: 'green', actor: 'CPU', detail: 'i 自增为 5，判断 5<5 为假，循环结束。for 循环共执行 5 次 (i=0,1,2,3,4)。' }, prediction: null, misconception: null, actor: 'CPU', target: 'control-flow', timing: 'loop-exit' },
    { step: 18, line: 17, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 15, 14, 15, 14, 15, 14, 15, 16], vars: { score: 85, grade: 'B', sum: 10, count: 0 }, highlightVar: 'count', isDanger: false, output: [], explanation: { icon: 'memory', text: '声明 int 变量 count = 0', color: 'yellow', actor: 'CPU', detail: 'count 初始化为 0，用于 while 循环计数。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:count', timing: 'main-loop' },
    { step: 19, line: 18, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 15, 14, 15, 14, 15, 14, 15, 16, 17], vars: { score: 85, grade: 'B', sum: 10, count: 0 }, highlightVar: 'count', isDanger: false, output: [], explanation: { icon: 'target', text: 'while 循环判断 count<3，即 0<3 为真', color: 'orange', actor: 'CPU', detail: 'while 循环先判断条件再执行循环体。如果初始条件就为假，循环体一次也不执行。' }, prediction: { question: 'while 循环执行几次？', options: ['2 次', '3 次', '4 次'], answer: 1 }, misconception: null, actor: 'CPU', target: 'control-flow', timing: 'loop-check' },
    { step: 20, line: 19, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 15, 14, 15, 14, 15, 14, 15, 16, 17, 18], vars: { score: 85, grade: 'B', sum: 10, count: 1 }, highlightVar: 'count', isDanger: false, output: [], explanation: { icon: 'bolt', text: '执行 count++，count 变为 1', color: 'green', actor: 'CPU', detail: 'count 自增 1。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:count', timing: 'loop-body' },
    { step: 21, line: 18, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 15, 14, 15, 14, 15, 14, 15, 16, 17, 18, 19], vars: { score: 85, grade: 'B', sum: 10, count: 1 }, highlightVar: 'count', isDanger: false, output: [], explanation: { icon: 'target', text: 'while 判断 count<3，即 1<3 为真', color: 'orange', actor: 'CPU', detail: '回到循环开始判断条件。' }, prediction: null, misconception: null, actor: 'CPU', target: 'control-flow', timing: 'loop-check' },
    { step: 22, line: 19, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 15, 14, 15, 14, 15, 14, 15, 16, 17, 18, 19, 18], vars: { score: 85, grade: 'B', sum: 10, count: 2 }, highlightVar: 'count', isDanger: false, output: [], explanation: { icon: 'bolt', text: '执行 count++，count 变为 2', color: 'green', actor: 'CPU', detail: 'count 自增 1。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:count', timing: 'loop-body' },
    { step: 23, line: 18, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 15, 14, 15, 14, 15, 14, 15, 16, 17, 18, 19, 18, 19], vars: { score: 85, grade: 'B', sum: 10, count: 2 }, highlightVar: 'count', isDanger: false, output: [], explanation: { icon: 'target', text: 'while 判断 count<3，即 2<3 为真', color: 'orange', actor: 'CPU', detail: '继续循环。' }, prediction: null, misconception: null, actor: 'CPU', target: 'control-flow', timing: 'loop-check' },
    { step: 24, line: 19, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 15, 14, 15, 14, 15, 14, 15, 16, 17, 18, 19, 18, 19, 18], vars: { score: 85, grade: 'B', sum: 10, count: 3 }, highlightVar: 'count', isDanger: false, output: [], explanation: { icon: 'bolt', text: '执行 count++，count 变为 3', color: 'green', actor: 'CPU', detail: 'count 自增 1，达到终止条件。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:count', timing: 'loop-body' },
    { step: 25, line: 20, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 15, 14, 15, 14, 15, 14, 15, 16, 17, 18, 19, 18, 19, 18, 19], vars: { score: 85, grade: 'B', sum: 10, count: 3 }, highlightVar: null, isDanger: false, output: [], explanation: { icon: 'check', text: 'while 判断 count<3，即 3<3 为假，退出循环', color: 'green', actor: 'CPU', detail: '循环结束。while 循环共执行 3 次 (count=0,1,2)。' }, prediction: null, misconception: null, actor: 'CPU', target: 'control-flow', timing: 'loop-exit' },
    { step: 26, line: 21, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 15, 14, 15, 14, 15, 14, 15, 16, 17, 18, 19, 18, 19, 18, 19, 18, 20], vars: { score: 85, grade: 'B', sum: 10, count: 3 }, highlightVar: null, isDanger: false, output: [{ type: 'success', text: 'grade=B, sum=10, count=3' }], explanation: { icon: 'terminal', text: 'printf 输出：grade=B, sum=10, count=3', color: 'green', actor: 'CPU', detail: '%c 输出字符 B，%d 输出整数 10 和 3。' }, prediction: null, misconception: null, actor: 'CPU', target: 'stdout', timing: 'main-loop' }
  ],
  summary: {
    oneLiner: 'if-else 处理多分支，for 适合已知次数循环，while 适合条件控制循环',
    pitfalls: [
      '未初始化的局部变量值不确定，sum=0 这样的初始化很重要',
      'for 循环 i<5 执行 5 次 (i=0,1,2,3,4)，i<=5 会执行 6 次导致越界',
      'while 循环先判断后执行，初始条件为假时循环体一次也不执行'
    ],
    transferQuestion: '如果将 for 循环条件改为 i<=5，sum 的最终值是多少？(原代码 sum=0+1+2+3+4=10)',
    miniExercise: {
      bugCode: 'for (int i = 0; i < 10; i++);\n    printf("%d", i);  // 这里有什么问题？',
      hint: 'for 循环后面多写了分号，循环体变成空语句'
    }
  }
};
