window.LESSON_DATA = {
  meta: {
    id: 'bt-arrays',
    title: '数组',
    chapter: 'basics-test',
    index: 5,
    filename: 'arrays.c',
    keyPoints: ['数组下标', '内存布局', '字符串']
  },
  codeLines: [
    { num: 1, tokens: [{ type: 'pp', text: '#include' }, { type: 'ws', text: ' ' }, { type: 'str', text: '<stdio.h>' }] },
    { num: 2, tokens: [{ type: 'ws', text: ' ' }] },
    { num: 3, tokens: [{ type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'fn', text: 'main' }, { type: 'punc', text: '()' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 4, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'nums' }, { type: 'punc', text: '[' }, { type: 'num', text: '5' }, { type: 'punc', text: ']' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }, { type: 'num', text: '1' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'num', text: '2' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'num', text: '3' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'num', text: '4' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'num', text: '5' }, { type: 'punc', text: '}' }, { type: 'punc', text: ';' }] },
    { num: 5, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'first' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'nums' }, { type: 'punc', text: '[' }, { type: 'num', text: '0' }, { type: 'punc', text: ']' }, { type: 'punc', text: ';' }, { type: 'ws', text: ' ' }, { type: 'cmt', text: '// 1' }] },
    { num: 6, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'last' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'nums' }, { type: 'punc', text: '[' }, { type: 'num', text: '4' }, { type: 'punc', text: ']' }, { type: 'punc', text: ';' }, { type: 'ws', text: ' ' }, { type: 'cmt', text: '// 5' }] },
    { num: 7, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'sum' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ';' }] },
    { num: 8, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'for' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '(' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ';' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' }, { type: 'ws', text: ' ' }, { type: 'op', text: '<' }, { type: 'ws', text: ' ' }, { type: 'num', text: '5' }, { type: 'punc', text: ';' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' }, { type: 'op', text: '++' }, { type: 'punc', text: ')' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 9, tokens: [{ type: 'ws', text: '        ' }, { type: 'id', text: 'sum' }, { type: 'ws', text: ' ' }, { type: 'op', text: '+=' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'nums' }, { type: 'punc', text: '[' }, { type: 'id', text: 'i' }, { type: 'punc', text: ']' }, { type: 'punc', text: ';' }] },
    { num: 10, tokens: [{ type: 'ws', text: '    ' }, { type: 'punc', text: '}' }] },
    { num: 11, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'matrix' }, { type: 'punc', text: '[' }, { type: 'num', text: '3' }, { type: 'punc', text: ']' }, { type: 'punc', text: '[' }, { type: 'num', text: '2' }, { type: 'punc', text: ']' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 12, tokens: [{ type: 'ws', text: '        ' }, { type: 'punc', text: '{' }, { type: 'num', text: '1' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'num', text: '2' }, { type: 'punc', text: '}' }, { type: 'punc', text: ',' }] },
    { num: 13, tokens: [{ type: 'ws', text: '        ' }, { type: 'punc', text: '{' }, { type: 'num', text: '3' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'num', text: '4' }, { type: 'punc', text: '}' }, { type: 'punc', text: ',' }] },
    { num: 14, tokens: [{ type: 'ws', text: '        ' }, { type: 'punc', text: '{' }, { type: 'num', text: '5' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'num', text: '6' }, { type: 'punc', text: '}' }] },
    { num: 15, tokens: [{ type: 'ws', text: '    ' }, { type: 'punc', text: '}' }, { type: 'punc', text: ';' }] },
    { num: 16, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'val' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'matrix' }, { type: 'punc', text: '[' }, { type: 'num', text: '1' }, { type: 'punc', text: ']' }, { type: 'punc', text: '[' }, { type: 'num', text: '0' }, { type: 'punc', text: ']' }, { type: 'punc', text: ';' }, { type: 'ws', text: ' ' }, { type: 'cmt', text: '// 3' }] },
    { num: 17, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'char' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'str' }, { type: 'punc', text: '[' }, { type: 'punc', text: ']' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'str', text: '"Hello"' }, { type: 'punc', text: ';' }] },
    { num: 18, tokens: [{ type: 'ws', text: '    ' }, { type: 'fn', text: 'printf' }, { type: 'punc', text: '(' }, { type: 'str', text: '"first=%d, last=%d, sum=%d\\n"' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'first' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'last' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'sum' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 19, tokens: [{ type: 'ws', text: '    ' }, { type: 'fn', text: 'printf' }, { type: 'punc', text: '(' }, { type: 'str', text: '"matrix[1][0]=%d, str=%s\\n"' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'val' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'str' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 20, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'return' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ';' }] },
    { num: 21, tokens: [{ type: 'punc', text: '}' }] }
  ],
  varConfig: [
    { key: 'nums', name: 'nums', type: 'int[5]', addr: '0x7ffc00', glowColor: 'rgba(34,197,94,0.35)', accentCls: 'text-green-400', badgeCls: 'text-green-400 border-green-500/30 bg-green-500/12', appearStep: 1 },
    { key: 'first', name: 'first', type: 'int', addr: '0x7ffc14', glowColor: 'rgba(59,130,246,0.35)', accentCls: 'text-blue-400', badgeCls: 'text-blue-400 border-blue-500/30 bg-blue-500/12', appearStep: 2 },
    { key: 'last', name: 'last', type: 'int', addr: '0x7ffc18', glowColor: 'rgba(249,115,22,0.35)', accentCls: 'text-orange-400', badgeCls: 'text-orange-400 border-orange-500/30 bg-orange-500/12', appearStep: 3 },
    { key: 'sum', name: 'sum', type: 'int', addr: '0x7ffc1c', glowColor: 'rgba(168,85,247,0.35)', accentCls: 'text-purple-400', badgeCls: 'text-purple-400 border-purple-500/30 bg-purple-500/12', appearStep: 4 },
    { key: 'i', name: 'i', type: 'int', addr: '0x7ffc20', glowColor: 'rgba(236,72,153,0.35)', accentCls: 'text-pink-400', badgeCls: 'text-pink-400 border-pink-500/30 bg-pink-500/12', appearStep: 5 },
    { key: 'val', name: 'val', type: 'int', addr: '0x7ffc24', glowColor: 'rgba(34,197,94,0.35)', accentCls: 'text-green-400', badgeCls: 'text-green-400 border-green-500/30 bg-green-500/12', appearStep: 11 }
  ],
  scenes: [
    { step: 0, line: -1, executedLines: [], vars: {}, highlightVar: null, isDanger: false, output: [], explanation: { icon: 'rocket', text: '点击播放，开始学习数组', color: 'blue', actor: null, detail: null }, prediction: null, misconception: null, actor: null, target: null, timing: null },
    { step: 1, line: 4, executedLines: [2, 3], vars: { nums: [1, 2, 3, 4, 5] }, highlightVar: 'nums', isDanger: false, output: [], explanation: { icon: 'memory', text: '声明 int 数组 nums[5] = {1,2,3,4,5}，连续分配 20 字节 (5×4)', color: 'yellow', actor: 'CPU', detail: '数组在内存中是连续存储的。nums[0] 在 0x7ffc00，nums[1] 在 0x7ffc04，依此类推。数组名 nums 表示首元素地址。' }, prediction: { question: '数组下标从几开始？', options: ['0', '1', '可配置'], answer: 0 }, misconception: null, actor: 'CPU', target: 'var:nums', timing: 'main-loop' },
    { step: 2, line: 5, executedLines: [2, 3, 4], vars: { nums: [1, 2, 3, 4, 5], first: 1 }, highlightVar: 'first', isDanger: false, output: [], explanation: { icon: 'pointer', text: 'nums[0] 访问第一个元素，值为 1', color: 'blue', actor: 'CPU', detail: '数组下标从 0 开始。nums[0] 表示访问首元素。CPU 计算地址：nums+0×4 = 0x7ffc00，读取 4 字节得到 1。' }, prediction: null, misconception: { title: '数组下标从 0 开始不是 1', text: 'C 语言数组下标从 0 开始。nums[0] 是第一个元素，nums[4] 是最后一个 (长度为 5 时)。访问 nums[5] 会越界。' }, actor: 'CPU', target: 'var:first', timing: 'main-loop' },
    { step: 3, line: 6, executedLines: [2, 3, 4, 5], vars: { nums: [1, 2, 3, 4, 5], first: 1, last: 5 }, highlightVar: 'last', isDanger: false, output: [], explanation: { icon: 'pointer', text: 'nums[4] 访问最后一个元素，值为 5', color: 'orange', actor: 'CPU', detail: '长度为 5 的数组，最后一个是下标 4 (5-1)。CPU 计算地址：nums+4×4 = 0x7ffc10，读取得到 5。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:last', timing: 'main-loop' },
    { step: 4, line: 7, executedLines: [2, 3, 4, 5, 6], vars: { nums: [1, 2, 3, 4, 5], first: 1, last: 5, sum: 0 }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'memory', text: '声明 sum = 0，用于累加数组元素', color: 'yellow', actor: 'CPU', detail: '累加器必须初始化为 0，否则结果是未定值。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:sum', timing: 'main-loop' },
    { step: 5, line: 8, executedLines: [2, 3, 4, 5, 6, 7], vars: { nums: [1, 2, 3, 4, 5], first: 1, last: 5, sum: 0, i: 0 }, highlightVar: 'i', isDanger: false, output: [], explanation: { icon: 'memory', text: 'for 循环初始化 i=0', color: 'blue', actor: 'CPU', detail: '循环变量 i 从 0 开始，遍历整个数组。' }, prediction: { question: '循环执行几次？', options: ['4 次 (0-3)', '5 次 (0-4)', '6 次 (0-5)'], answer: 1 }, misconception: null, actor: 'CPU', target: 'var:i', timing: 'loop-init' },
    { step: 6, line: 9, executedLines: [2, 3, 4, 5, 6, 7, 8], vars: { nums: [1, 2, 3, 4, 5], first: 1, last: 5, sum: 0, i: 0 }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'bolt', text: '第一次循环：sum += nums[0] = 0 + 1 = 1', color: 'green', actor: 'CPU', detail: 'i=0 时，nums[0]=1，sum 变为 1。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:sum', timing: 'loop-body' },
    { step: 7, line: 8, executedLines: [2, 3, 4, 5, 6, 7, 8, 9], vars: { nums: [1, 2, 3, 4, 5], first: 1, last: 5, sum: 1, i: 1 }, highlightVar: 'i', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'i++ 后 i=1，继续循环', color: 'purple', actor: 'CPU', detail: 'i 自增为 1，判断 1<5 为真。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:i', timing: 'loop-iter' },
    { step: 8, line: 9, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 8], vars: { nums: [1, 2, 3, 4, 5], first: 1, last: 5, sum: 3, i: 1 }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'bolt', text: '第二次循环：sum += nums[1] = 1 + 2 = 3', color: 'green', actor: 'CPU', detail: 'i=1 时，nums[1]=2，sum 变为 3。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:sum', timing: 'loop-body' },
    { step: 9, line: 8, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 8, 9], vars: { nums: [1, 2, 3, 4, 5], first: 1, last: 5, sum: 3, i: 2 }, highlightVar: 'i', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'i++ 后 i=2，继续循环', color: 'purple', actor: 'CPU', detail: 'i 自增为 2，判断 2<5 为真。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:i', timing: 'loop-iter' },
    { step: 10, line: 9, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 8, 9, 8], vars: { nums: [1, 2, 3, 4, 5], first: 1, last: 5, sum: 6, i: 2 }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'bolt', text: '第三次循环：sum += nums[2] = 3 + 3 = 6', color: 'green', actor: 'CPU', detail: 'i=2 时，nums[2]=3，sum 变为 6。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:sum', timing: 'loop-body' },
    { step: 11, line: 8, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 8, 9, 8, 9], vars: { nums: [1, 2, 3, 4, 5], first: 1, last: 5, sum: 6, i: 3 }, highlightVar: 'i', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'i++ 后 i=3，继续循环', color: 'purple', actor: 'CPU', detail: 'i 自增为 3，判断 3<5 为真。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:i', timing: 'loop-iter' },
    { step: 12, line: 9, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 8, 9, 8, 9, 8], vars: { nums: [1, 2, 3, 4, 5], first: 1, last: 5, sum: 10, i: 3 }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'bolt', text: '第四次循环：sum += nums[3] = 6 + 4 = 10', color: 'green', actor: 'CPU', detail: 'i=3 时，nums[3]=4，sum 变为 10。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:sum', timing: 'loop-body' },
    { step: 13, line: 8, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 8, 9, 8, 9, 8, 9], vars: { nums: [1, 2, 3, 4, 5], first: 1, last: 5, sum: 10, i: 4 }, highlightVar: 'i', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'i++ 后 i=4，继续循环', color: 'purple', actor: 'CPU', detail: 'i 自增为 4，判断 4<5 为真，最后一次。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:i', timing: 'loop-iter' },
    { step: 14, line: 9, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 8, 9, 8, 9, 8, 9, 8], vars: { nums: [1, 2, 3, 4, 5], first: 1, last: 5, sum: 15, i: 4 }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'bolt', text: '第五次循环：sum += nums[4] = 10 + 5 = 15', color: 'green', actor: 'CPU', detail: 'i=4 时，nums[4]=5，sum 变为 15。1+2+3+4+5=15。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:sum', timing: 'loop-body' },
    { step: 15, line: 10, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 8, 9, 8, 9, 8, 9, 8, 9], vars: { nums: [1, 2, 3, 4, 5], first: 1, last: 5, sum: 15, i: 4 }, highlightVar: null, isDanger: false, output: [], explanation: { icon: 'check', text: 'i++ 后 i=5，判断 i<5 为假，退出循环', color: 'green', actor: 'CPU', detail: '循环结束。sum 累加了所有元素得到 15。' }, prediction: null, misconception: null, actor: 'CPU', target: 'control-flow', timing: 'loop-exit' },
    { step: 16, line: 11, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 8, 9, 8, 9, 8, 9, 8, 9, 10], vars: { nums: [1, 2, 3, 4, 5], first: 1, last: 5, sum: 15 }, highlightVar: null, isDanger: false, output: [], explanation: { icon: 'memory', text: '声明二维数组 matrix[3][2]，3 行 2 列', color: 'yellow', actor: 'CPU', detail: '二维数组在内存中按行优先顺序连续存储。matrix[0][0] 在最低地址，然后是 matrix[0][1]，再是 matrix[1][0]，依此类推。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:matrix', timing: 'main-loop' },
    { step: 17, line: 16, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 8, 9, 8, 9, 8, 9, 8, 9, 10, 11, 12, 13, 14, 15], vars: { nums: [1, 2, 3, 4, 5], first: 1, last: 5, sum: 15, val: 3 }, highlightVar: 'val', isDanger: false, output: [], explanation: { icon: 'pointer', text: 'matrix[1][0] 访问第 2 行第 1 列，值为 3', color: 'blue', actor: 'CPU', detail: '二维数组下标也是从 0 开始。matrix[1][0] 表示第 2 行 (下标 1) 第 1 列 (下标 0)。CPU 计算地址：matrix + (1×2+0)×4。' }, prediction: { question: 'matrix[2][1] 的值是多少？', options: ['4', '5', '6'], answer: 2 }, misconception: null, actor: 'CPU', target: 'var:val', timing: 'main-loop' },
    { step: 18, line: 17, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 8, 9, 8, 9, 8, 9, 8, 9, 10, 11, 12, 13, 14, 15, 16], vars: { nums: [1, 2, 3, 4, 5], first: 1, last: 5, sum: 15, val: 3, str: 'Hello\u0000' }, highlightVar: 'str', isDanger: false, output: [], explanation: { icon: 'memory', text: '声明字符数组 str = "Hello"，自动添加\\0 终止符', color: 'green', actor: 'CPU', detail: '字符串字面量 "Hello" 实际是 6 个字符：\'H\',\'e\',\'l\',\'l\',\'o\',\'\\0\'。\\0 是字符串终止符，ASCII 码为 0。编译器自动添加。' }, prediction: null, misconception: { title: '字符串末尾有隐藏的\\0', text: 'C 语言字符串以\\0 结尾。"Hello" 实际占用 6 字节，不是 5 字节。\\0 是字符串终止标志，printf("%s") 遇到\\0 才停止输出。' }, actor: 'CPU', target: 'var:str', timing: 'main-loop' },
    { step: 19, line: 18, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 8, 9, 8, 9, 8, 9, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17], vars: { nums: [1, 2, 3, 4, 5], first: 1, last: 5, sum: 15, val: 3, str: 'Hello\u0000' }, highlightVar: null, isDanger: false, output: [{ type: 'success', text: 'first=1, last=5, sum=15' }], explanation: { icon: 'terminal', text: 'printf 输出：first=1, last=5, sum=15', color: 'green', actor: 'CPU', detail: '格式化输出数组元素计算结果。' }, prediction: null, misconception: null, actor: 'CPU', target: 'stdout', timing: 'main-loop' },
    { step: 20, line: 19, executedLines: [2, 3, 4, 5, 6, 7, 8, 9, 8, 9, 8, 9, 8, 9, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18], vars: { nums: [1, 2, 3, 4, 5], first: 1, last: 5, sum: 15, val: 3, str: 'Hello\u0000' }, highlightVar: null, isDanger: false, output: [{ type: 'success', text: 'first=1, last=5, sum=15' }, { type: 'success', text: 'matrix[1][0]=3, str=Hello' }], explanation: { icon: 'terminal', text: 'printf 输出：matrix[1][0]=3, str=Hello', color: 'green', actor: 'CPU', detail: '%s 格式符输出字符串，遇到\\0 自动停止。' }, prediction: null, misconception: null, actor: 'CPU', target: 'stdout', timing: 'main-loop' }
  ],
  summary: {
    oneLiner: '数组是连续内存块，下标从 0 开始，字符串以\\0 结尾',
    pitfalls: [
      '数组下标从 0 开始不是 1，长度为 5 的数组有效下标是 0~4',
      '访问 arr[5] 会越界 (长度 5 时)，可能读取垃圾数据或崩溃',
      '字符串 "Hello" 实际占用 6 字节，末尾有隐藏的\\0 终止符'
    ],
    transferQuestion: '如果定义 int arr[5]，然后执行 arr[5] = 100，会发生什么？',
    miniExercise: {
      bugCode: 'char str[5] = "Hello";\nprintf("%s", str);  // 这样写有什么问题？',
      hint: '"Hello" 有 6 个字符 (含\\0)，数组只有 5 字节空间'
    }
  }
};
