window.LESSON_DATA = {
  meta: {
    id: 'l3-file',
    title: '文件操作',
    chapter: 'level3',
    index: 2,
    filename: 'file-io.c',
    keyPoints: ['fopen', 'fread', 'fwrite']
  },
  codeLines: [
    { num: 1, tokens: [{ type: 'pp', text: '#include' }, { type: 'ws', text: ' ' }, { type: 'str', text: '<stdio.h>' }] },
    { num: 2, tokens: [{ type: 'ws', text: ' ' }] },
    { num: 3, tokens: [{ type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'fn', text: 'main' }, { type: 'punc', text: '()' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 4, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'FILE' }, { type: 'ws', text: ' ' }, { type: 'op', text: '*' }, { type: 'id', text: 'fp' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'fn', text: 'fopen' }, { type: 'punc', text: '(' }, { type: 'str', text: '"data.bin"' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'str', text: '"wb"' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 5, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'if' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '(' }, { type: 'id', text: 'fp' }, { type: 'ws', text: ' ' }, { type: 'op', text: '==' }, { type: 'ws', text: ' ' }, { type: 'kw', text: 'NULL' }, { type: 'punc', text: ')' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 6, tokens: [{ type: 'ws', text: '        ' }, { type: 'fn', text: 'printf' }, { type: 'punc', text: '(' }, { type: 'str', text: '"[ERROR] Cannot open file!\\\\n"' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 7, tokens: [{ type: 'ws', text: '        ' }, { type: 'kw', text: 'return' }, { type: 'ws', text: ' ' }, { type: 'num', text: '1' }, { type: 'punc', text: ';' }] },
    { num: 8, tokens: [{ type: 'ws', text: '    ' }, { type: 'punc', text: '}' }] },
    { num: 9, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'data' }, { type: 'punc', text: '[' }, { type: 'num', text: '5' }, { type: 'punc', text: ']' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }, { type: 'num', text: '10' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'num', text: '20' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'num', text: '30' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'num', text: '40' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'num', text: '50' }, { type: 'punc', text: '}' }, { type: 'punc', text: ';' }] },
    { num: 10, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'size_t' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'written' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'fn', text: 'fwrite' }, { type: 'punc', text: '(' }, { type: 'id', text: 'data' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'kw', text: 'sizeof' }, { type: 'punc', text: '(' }, { type: 'kw', text: 'int' }, { type: 'punc', text: ')' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'num', text: '5' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'fp' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 11, tokens: [{ type: 'ws', text: '    ' }, { type: 'fn', text: 'printf' }, { type: 'punc', text: '(' }, { type: 'str', text: '"Wrote %zu integers\\\\n"' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'written' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 12, tokens: [{ type: 'ws', text: '    ' }, { type: 'fn', text: 'fclose' }, { type: 'punc', text: '(' }, { type: 'id', text: 'fp' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 13, tokens: [{ type: 'ws', text: ' ' }] },
    { num: 14, tokens: [{ type: 'ws', text: '    ' }, { type: 'id', text: 'fp' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'fn', text: 'fopen' }, { type: 'punc', text: '(' }, { type: 'str', text: '"data.bin"' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'str', text: '"rb"' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 15, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'buf' }, { type: 'punc', text: '[' }, { type: 'num', text: '5' }, { type: 'punc', text: ']' }, { type: 'punc', text: ';' }] },
    { num: 16, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'size_t' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'read' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'fn', text: 'fread' }, { type: 'punc', text: '(' }, { type: 'id', text: 'buf' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'kw', text: 'sizeof' }, { type: 'punc', text: '(' }, { type: 'kw', text: 'int' }, { type: 'punc', text: ')' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'num', text: '5' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'fp' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 17, tokens: [{ type: 'ws', text: '    ' }, { type: 'fn', text: 'printf' }, { type: 'punc', text: '(' }, { type: 'str', text: '"Read: %d %d %d %d %d\\\\n"' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'buf' }, { type: 'punc', text: '[' }, { type: 'num', text: '0' }, { type: 'punc', text: ']' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'buf' }, { type: 'punc', text: '[' }, { type: 'num', text: '1' }, { type: 'punc', text: ']' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'buf' }, { type: 'punc', text: '[' }, { type: 'num', text: '2' }, { type: 'punc', text: ']' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'buf' }, { type: 'punc', text: '[' }, { type: 'num', text: '3' }, { type: 'punc', text: ']' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'buf' }, { type: 'punc', text: '[' }, { type: 'num', text: '4' }, { type: 'punc', text: ']' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 18, tokens: [{ type: 'ws', text: '    ' }, { type: 'fn', text: 'fclose' }, { type: 'punc', text: '(' }, { type: 'id', text: 'fp' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 19, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'return' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ';' }] },
    { num: 20, tokens: [{ type: 'punc', text: '}' }] }
  ],
  varConfig: [
    { key: 'fp', name: 'fp', type: 'FILE*', addr: '0x7ffc00', glowColor: 'rgba(34,197,94,0.35)', accentCls: 'text-green-400', badgeCls: 'text-green-400 border-green-500/30 bg-green-500/12', appearStep: 1 },
    { key: 'data', name: 'data', type: 'int[5]', addr: '0x7ffc04', glowColor: 'rgba(59,130,246,0.35)', accentCls: 'text-blue-400', badgeCls: 'text-blue-400 border-blue-500/30 bg-blue-500/12', appearStep: 3 },
    { key: 'written', name: 'written', type: 'size_t', addr: '0x7ffc18', glowColor: 'rgba(168,85,247,0.35)', accentCls: 'text-purple-400', badgeCls: 'text-purple-400 border-purple-500/30 bg-purple-500/12', appearStep: 4 },
    { key: 'buf', name: 'buf', type: 'int[5]', addr: '0x7ffc1c', glowColor: 'rgba(249,115,22,0.35)', accentCls: 'text-orange-400', badgeCls: 'text-orange-400 border-orange-500/30 bg-orange-500/12', appearStep: 7 }
  ],
  scenes: [
    { step: 0, line: -1, executedLines: [], vars: {}, highlightVar: null, isDanger: false, output: [], explanation: { icon: 'rocket', text: '点击播放，开始学习文件操作', color: 'blue', actor: null, detail: null }, prediction: null, misconception: null, actor: null, target: null, timing: null },
    { step: 1, line: 4, executedLines: [3], vars: { fp: 'file_addr' }, highlightVar: 'fp', isDanger: false, output: [], explanation: { icon: 'folder', text: 'fopen("data.bin", "wb") 以写二进制打开文件', color: 'yellow', actor: 'CPU', detail: 'fopen 打开或创建文件。"wb" 表示写二进制模式：文件不存在则创建，存在则清空。返回 FILE* 文件指针，用于后续操作。' }, prediction: { question: '"wb" 模式是什么意思？', options: ['读文本', '写二进制', '追加文本'], answer: 1 }, misconception: null, actor: 'CPU', target: 'var:fp', timing: 'main-loop' },
    { step: 2, line: 5, executedLines: [3, 4], vars: { fp: 'file_addr' }, highlightVar: null, isDanger: false, output: [], explanation: { icon: 'target', text: '检查 fp == NULL，文件是否打开成功', color: 'orange', actor: 'CPU', detail: 'fopen 失败返回 NULL（如磁盘满、权限不足）。必须检查！这是健壮程序的基本要求。' }, prediction: null, misconception: null, actor: 'CPU', target: 'control-flow', timing: 'condition-check' },
    { step: 3, line: 9, executedLines: [3, 4, 5, 6, 7, 8], vars: { fp: 'file_addr', data: [10, 20, 30, 40, 50] }, highlightVar: 'data', isDanger: false, output: [], explanation: { icon: 'memory', text: '初始化 int data[5] = {10,20,30,40,50}', color: 'blue', actor: 'CPU', detail: 'data 数组包含 5 个整数，将要写入文件。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:data', timing: 'main-loop' },
    { step: 4, line: 10, executedLines: [3, 4, 5, 6, 7, 8, 9], vars: { fp: 'file_addr', data: [10, 20, 30, 40, 50], written: 5 }, highlightVar: 'written', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'fwrite(data, sizeof(int), 5, fp) 写入 5 个整数', color: 'green', actor: 'CPU', detail: 'fwrite 参数：数据指针、每个元素大小、元素个数、文件指针。写入 5×4=20 字节到文件。返回实际写入的元素个数。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:written', timing: 'main-loop' },
    { step: 5, line: 11, executedLines: [3, 4, 5, 6, 7, 8, 9, 10], vars: { fp: 'file_addr', data: [10, 20, 30, 40, 50], written: 5 }, highlightVar: null, isDanger: false, output: [{ type: 'success', text: 'Wrote 5 integers' }], explanation: { icon: 'terminal', text: 'printf 输出 Wrote 5 integers', color: 'green', actor: 'CPU', detail: '%zu 是 size_t 类型的格式符。验证成功写入 5 个整数。' }, prediction: null, misconception: null, actor: 'CPU', target: 'stdout', timing: 'main-loop' },
    { step: 6, line: 12, executedLines: [3, 4, 5, 6, 7, 8, 9, 10, 11], vars: { fp: null }, highlightVar: 'fp', isDanger: false, output: [{ type: 'success', text: 'Wrote 5 integers' }], explanation: { icon: 'check', text: 'fclose(fp) 关闭文件', color: 'green', actor: 'CPU', detail: 'fclose 刷新缓冲区并将文件内容写入磁盘。必须关闭！否则数据可能丢失（还在缓冲区）。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:fp', timing: 'main-loop' },
    { step: 7, line: 14, executedLines: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], vars: { fp: 'file_addr', buf: [0, 0, 0, 0, 0] }, highlightVar: 'buf', isDanger: false, output: [{ type: 'success', text: 'Wrote 5 integers' }], explanation: { icon: 'folder', text: 'fopen("data.bin", "rb") 以读二进制打开文件', color: 'green', actor: 'CPU', detail: '"rb" 表示读二进制模式。重新打开刚才写入的文件，准备读取。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:fp', timing: 'main-loop' },
    { step: 8, line: 16, executedLines: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], vars: { fp: 'file_addr', buf: [10, 20, 30, 40, 50], read: 5 }, highlightVar: 'read', isDanger: false, output: [{ type: 'success', text: 'Wrote 5 integers' }], explanation: { icon: 'bolt', text: 'fread(buf, sizeof(int), 5, fp) 读取 5 个整数', color: 'green', actor: 'CPU', detail: 'fread 从文件读取数据到 buf 数组。参数与 fwrite 类似。返回实际读取的元素个数。读取 5×4=20 字节。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:read', timing: 'main-loop' },
    { step: 9, line: 17, executedLines: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], vars: { fp: 'file_addr', buf: [10, 20, 30, 40, 50], read: 5 }, highlightVar: null, isDanger: false, output: [{ type: 'success', text: 'Wrote 5 integers' }, { type: 'success', text: 'Read: 10 20 30 40 50' }], explanation: { icon: 'terminal', text: 'printf 输出读取的数据：10 20 30 40 50', color: 'green', actor: 'CPU', detail: '验证读取的数据与写入的完全一致。二进制文件读写是嵌入式系统中保存配置、日志的常用方式。' }, prediction: null, misconception: null, actor: 'CPU', target: 'stdout', timing: 'main-loop' },
    { step: 10, line: 18, executedLines: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17], vars: { fp: null }, highlightVar: 'fp', isDanger: false, output: [{ type: 'success', text: 'Wrote 5 integers' }, { type: 'success', text: 'Read: 10 20 30 40 50' }], explanation: { icon: 'check', text: 'fclose(fp) 关闭文件', color: 'green', actor: 'CPU', detail: '读取完成后关闭文件，释放资源。完整的文件操作流程：fopen → 读写 → fclose。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:fp', timing: 'main-loop' }
  ],
  summary: {
    oneLiner: 'fopen 打开文件，fwrite/fread 读写二进制，fclose 关闭，必须检查 NULL',
    pitfalls: [
      'fopen 失败返回 NULL，必须检查（磁盘满、权限不足等）',
      'fwrite/fread 后要检查返回值，确认实际读写的元素个数',
      '文件操作后必须 fclose 关闭，否则数据可能丢失在缓冲区'
    ],
    transferQuestion: '如果用"rb"模式打开不存在的文件，会发生什么？',
    miniExercise: {
      bugCode: 'FILE *fp = fopen("data.txt", "r");\\n// 直接 fwrite 写入，忘记检查 fp 是否为 NULL',
      hint: 'fopen 失败 fp 为 NULL，对 NULL 指针操作会导致程序崩溃'
    }
  }
};
