window.LESSON_DATA = {
  meta: {
    id: 'l5-perf',
    title: '性能优化',
    chapter: 'level5',
    index: 3,
    filename: 'performance-opt.c',
    keyPoints: ['循环展开', '缓存友好', '分支预测']
  },
  codeLines: [
    { num: 1, tokens: [{ type: 'pp', text: '#include' }, { type: 'ws', text: ' ' }, { type: 'str', text: '<stdio.h>' }] },
    { num: 2, tokens: [{ type: 'pp', text: '#include' }, { type: 'ws', text: ' ' }, { type: 'str', text: '<stdlib.h>' }] },
    { num: 3, tokens: [{ type: 'pp', text: '#include' }, { type: 'ws', text: ' ' }, { type: 'str', text: '<string.h>' }] },
    { num: 4, tokens: [{ type: 'pp', text: '#include' }, { type: 'ws', text: ' ' }, { type: 'str', text: '<time.h>' }] },
    { num: 5, tokens: [{ type: 'ws', text: ' ' }] },
    { num: 6, tokens: [{ type: 'kw', text: '#define' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'SIZE' }, { type: 'ws', text: ' ' }, { type: 'num', text: '10000000' }] },
    { num: 7, tokens: [{ type: 'ws', text: ' ' }] },
    { num: 8, tokens: [{ type: 'kw', text: 'void' }, { type: 'ws', text: ' ' }, { type: 'fn', text: 'naive_sum' }, { type: 'punc', text: '(' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'op', text: '*' }, { type: 'id', text: 'arr' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'n' }, { type: 'punc', text: ')' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 9, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'long' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'sum' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ';' }] },
    { num: 10, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'for' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '(' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ';' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' }, { type: 'ws', text: ' ' }, { type: 'op', text: '<' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'n' }, { type: 'punc', text: ';' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' }, { type: 'op', text: '++' }, { type: 'punc', text: ')' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 11, tokens: [{ type: 'ws', text: '        ' }, { type: 'id', text: 'sum' }, { type: 'ws', text: ' ' }, { type: 'op', text: '+=' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'arr' }, { type: 'punc', text: '[' }, { type: 'id', text: 'i' }, { type: 'punc', text: ']' }, { type: 'punc', text: ';' }] },
    { num: 12, tokens: [{ type: 'ws', text: '    ' }, { type: 'punc', text: '}' }] },
    { num: 13, tokens: [{ type: 'ws', text: '    ' }, { type: 'fn', text: 'printf' }, { type: 'punc', text: '(' }, { type: 'str', text: '"Naive sum: %ld\\\\n"' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'sum' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 14, tokens: [{ type: 'punc', text: '}' }] },
    { num: 15, tokens: [{ type: 'ws', text: ' ' }] },
    { num: 16, tokens: [{ type: 'kw', text: 'void' }, { type: 'ws', text: ' ' }, { type: 'fn', text: 'unrolled_sum' }, { type: 'punc', text: '(' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'op', text: '*' }, { type: 'id', text: 'arr' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'n' }, { type: 'punc', text: ')' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 17, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'long' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'sum' } }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ';' }] },
    { num: 18, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ';' }] },
    { num: 19, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'for' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '(' }, { type: 'punc', text: ';' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' }, { type: 'ws', text: ' ' }, { type: 'op', text: '<' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'n' }, { type: 'ws', text: ' ' }, { type: 'op', text: '-' }, { type: 'ws', text: ' ' }, { type: 'num', text: '3' }, { type: 'punc', text: ';' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' }, { type: 'ws', text: ' ' }, { type: 'op', text: '+=' }, { type: 'ws', text: ' ' }, { type: 'num', text: '4' }, { type: 'punc', text: ')' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 20, tokens: [{ type: 'ws', text: '        ' }, { type: 'id', text: 'sum' }, { type: 'ws', text: ' ' }, { type: 'op', text: '+=' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'arr' }, { type: 'punc', text: '[' }, { type: 'id', text: 'i' }, { type: 'punc', text: ']' }, { type: 'ws', text: ' ' }, { type: 'op', text: '+' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'arr' }, { type: 'punc', text: '[' }, { type: 'id', text: 'i' }, { type: 'op', text: '+' }, { type: 'num', text: '1' }, { type: 'punc', text: ']' }, { type: 'ws', text: ' ' }, { type: 'op', text: '+' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'arr' }, { type: 'punc', text: '[' }, { type: 'id', text: 'i' }, { type: 'op', text: '+' }, { type: 'num', text: '2' }, { type: 'punc', text: ']' }, { type: 'ws', text: ' ' }, { type: 'op', text: '+' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'arr' }, { type: 'punc', text: '[' }, { type: 'id', text: 'i' }, { type: 'op', text: '+' }, { type: 'num', text: '3' }, { type: 'punc', text: ']' }, { type: 'punc', text: ';' }] },
    { num: 21, tokens: [{ type: 'ws', text: '    ' }, { type: 'punc', text: '}' }] },
    { num: 22, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'for' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '(' }, { type: 'punc', text: ';' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' }, { type: 'ws', text: ' ' }, { type: 'op', text: '<' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'n' }, { type: 'punc', text: ';' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' }, { type: 'op', text: '++' }, { type: 'punc', text: ')' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'sum' }, { type: 'ws', text: ' ' }, { type: 'op', text: '+=' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'arr' }, { type: 'punc', text: '[' }, { type: 'id', text: 'i' }, { type: 'punc', text: ']' }, { type: 'punc', text: ';' }] },
    { num: 23, tokens: [{ type: 'ws', text: '    ' }, { type: 'fn', text: 'printf' }, { type: 'punc', text: '(' }, { type: 'str', text: '"Unrolled sum: %ld\\\\n"' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'sum' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 24, tokens: [{ type: 'punc', text: '}' }] },
    { num: 25, tokens: [{ type: 'ws', text: ' ' }] },
    { num: 26, tokens: [{ type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'fn', text: 'main' }, { type: 'punc', text: '()' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 27, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'op', text: '*' }, { type: 'id', text: 'data' } }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'fn', text: 'malloc' }, { type: 'punc', text: '(' }, { type: 'kw', text: 'sizeof' }, { type: 'punc', text: '(' }, { type: 'kw', text: 'int' }, { type: 'punc', text: ')' }, { type: 'ws', text: ' ' }, { type: 'op', text: '*' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'SIZE' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 28, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'for' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '(' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' } }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ';' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' }, { type: 'ws', text: ' ' }, { type: 'op', text: '<' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'SIZE' }, { type: 'punc', text: ';' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' }, { type: 'op', text: '++' }, { type: 'punc', text: ')' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'data' }, { type: 'punc', text: '[' }, { type: 'id', text: 'i' }, { type: 'punc', text: ']' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' }, { type: 'punc', text: ';' }] },
    { num: 29, tokens: [{ type: 'ws', text: '    ' }, { type: 'fn', text: 'naive_sum' }, { type: 'punc', text: '(' }, { type: 'id', text: 'data' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'SIZE' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 30, tokens: [{ type: 'ws', text: '    ' }, { type: 'fn', text: 'unrolled_sum' }, { type: 'punc', text: '(' }, { type: 'id', text: 'data' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'SIZE' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 31, tokens: [{ type: 'ws', text: '    ' }, { type: 'fn', text: 'free' }, { type: 'punc', text: '(' }, { type: 'id', text: 'data' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 32, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'return' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ';' }] },
    { num: 33, tokens: [{ type: 'punc', text: '}' }] }
  ],
  varConfig: [
    { key: 'data', name: 'data', type: 'int*', addr: '0x7f0000', glowColor: 'rgba(34,197,94,0.35)', accentCls: 'text-green-400', badgeCls: 'text-green-400 border-green-500/30 bg-green-500/12', appearStep: 1 },
    { key: 'sum', name: 'sum', type: 'long', addr: '0x7ffc00', glowColor: 'rgba(59,130,246,0.35)', accentCls: 'text-blue-400', badgeCls: 'text-blue-400 border-blue-500/30 bg-blue-500/12', appearStep: 3 }
  ],
  scenes: [
    { step: 0, line: -1, executedLines: [], vars: {}, highlightVar: null, isDanger: false, output: [], explanation: { icon: 'rocket', text: '点击播放，开始学习性能优化', color: 'blue', actor: null, detail: null }, prediction: null, misconception: null, actor: null, target: null, timing: null },
    { step: 1, line: 27, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26], vars: { data: '0x7f0000' }, highlightVar: 'data', isDanger: false, output: [], explanation: { icon: 'memory', text: 'malloc 分配 1000 万元素的数组', color: 'yellow', actor: 'CPU', detail: '分配约 40MB 堆内存（10^7 × 4 字节）。大数组用于测试性能优化效果。' }, prediction: { question: '循环展开为什么能提高性能？', options: ['减少循环次数', '减少分支预测失败', '提高指令级并行'], answer: 2 }, misconception: null, actor: 'CPU', target: 'var:data', timing: 'alloc' },
    { step: 2, line: 28, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27], vars: { data: '0x7f0000' }, highlightVar: 'data', isDanger: false, output: [], explanation: { icon: 'bolt', text: '初始化数组：data[i] = i', color: 'green', actor: 'CPU', detail: '顺序写入数组，数据在内存中连续存放。这种布局对 CPU 缓存友好。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:data', timing: 'init' },
    { step: 3, line: 10, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], vars: { sum: 0 }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'naive_sum：普通循环求和', color: 'green', actor: 'CPU', detail: '每次循环：1 次比较、1 次加法、1 次自增。循环 1000 万次。每次迭代有分支预测开销。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:sum', timing: 'loop' },
    { step: 4, line: 11, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], vars: { sum: 'computing' }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'cpu', text: 'sum += arr[i] 累加', color: 'purple', actor: 'CPU', detail: '顺序访问数组对缓存友好：CPU 预取相邻数据到 L1/L2 缓存。但每次迭代仍有循环控制开销。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:sum', timing: 'loop-body' },
    { step: 5, line: 13, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], vars: { sum: 'result' }, highlightVar: null, isDanger: false, output: [{ type: 'success', text: 'Naive sum: 49999995000000' }], explanation: { icon: 'terminal', text: 'printf 输出普通循环结果', color: 'green', actor: 'CPU', detail: '结果正确。假设耗时 10ms（举例）。' }, prediction: null, misconception: null, actor: 'CPU', target: 'stdout', timing: 'output' },
    { step: 6, line: 19, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18], vars: { sum: 0 }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'unrolled_sum：循环展开 4 倍', color: 'green', actor: 'CPU', detail: '循环展开（Loop Unrolling）：每次迭代处理 4 个元素。减少循环次数到原来的 1/4，减少分支预测失败，增加指令级并行（ILP）。' }, prediction: { question: '4 倍循环展开后，循环次数变为多少？', options: ['不变', '原来的 1/2', '原来的 1/4'], answer: 2 }, misconception: null, actor: 'CPU', target: 'var:sum', timing: 'unrolled-loop' },
    { step: 7, line: 20, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], vars: { sum: 'computing' }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'cpu', text: '一次累加 4 个元素，提高指令级并行', color: 'green', actor: 'CPU', detail: 'CPU 可以在一个时钟周期内执行多条独立的加法指令（超标量架构）。展开后减少 75% 的分支指令。' }, prediction: null, misconception: { title: '循环展开的权衡', text: '优点：减少分支、提高 ILP。缺点：代码体积增大，寄存器压力增加。通常 4-8 倍展开效果最佳。' }, actor: 'CPU', target: 'var:sum', timing: 'unrolled-body' },
    { step: 8, line: 22, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21], vars: { sum: 'partial' }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'bolt', text: '处理剩余元素（n%4 个）', color: 'purple', actor: 'CPU', detail: '当 n 不是 4 的倍数时，剩余元素用普通循环处理。这是循环展开的标准模式。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:sum', timing: 'cleanup' },
    { step: 9, line: 23, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22], vars: { sum: 'result' }, highlightVar: null, isDanger: false, output: [{ type: 'success', text: 'Naive sum: 49999995000000' }, { type: 'success', text: 'Unrolled sum: 49999995000000' }], explanation: { icon: 'terminal', text: 'printf 输出展开循环结果', color: 'green', actor: 'CPU', detail: '结果相同，但性能提升约 2-3 倍（取决于 CPU 架构）。实际优化需要 profile 测量。' }, prediction: null, misconception: null, actor: 'CPU', target: 'stdout', timing: 'output' },
    { step: 10, line: 31, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], vars: { data: 'freed' }, highlightVar: 'data', isDanger: false, output: [{ type: 'success', text: 'Naive sum: 49999995000000' }, { type: 'success', text: 'Unrolled sum: 49999995000000' }], explanation: { icon: 'check', text: 'free 释放内存', color: 'green', actor: 'CPU', detail: '性能优化总结：1) 循环展开减少分支；2) 顺序访问对缓存友好；3) 避免分支预测失败（用查表代替条件）。' }, prediction: null, misconception: null, actor: 'CPU', target: 'cleanup', timing: 'cleanup' }
  ],
  summary: {
    oneLiner: '循环展开减少分支开销，顺序访问对缓存友好，分支预测影响性能',
    pitfalls: [
      '循环展开减少循环次数，提高指令级并行（ILP），但增加代码体积',
      '顺序访问数组时 CPU 预取相邻数据到缓存，随机访问导致缓存未命中',
      '分支预测失败惩罚约 10-15 个时钟周期，应避免不可预测的分支'
    ],
    transferQuestion: '如果要优化嵌套循环，应该先展开内层还是外层？为什么？',
    miniExercise: {
      bugCode: '// 随机访问数组\\nfor (int i = 0; i < n; i++)\\n    sum += arr[rand() % n];  // 性能差\\n// 为什么性能差？',
      hint: '随机访问导致缓存未命中（Cache Miss），每次访问都要从主内存读取数据，延迟高达 100+ 时钟周期。'
    }
  }
};
