window.LESSON_DATA = {
  meta: {
    id: 'l4-network',
    title: '网络编程',
    chapter: 'level4',
    index: 3,
    filename: 'network-socket.c',
    keyPoints: ['socket', 'bind', 'listen', 'accept']
  },
  codeLines: [
    { num: 1, tokens: [{ type: 'pp', text: '#include' }, { type: 'ws', text: ' ' }, { type: 'str', text: '<stdio.h>' }] },
    { num: 2, tokens: [{ type: 'pp', text: '#include' }, { type: 'ws', text: ' ' }, { type: 'str', text: '<stdlib.h>' }] },
    { num: 3, tokens: [{ type: 'pp', text: '#include' }, { type: 'ws', text: ' ' }, { type: 'str', text: '<string.h>' }] },
    { num: 4, tokens: [{ type: 'pp', text: '#include' }, { type: 'ws', text: ' ' }, { type: 'str', text: '<unistd.h>' }] },
    { num: 5, tokens: [{ type: 'pp', text: '#include' }, { type: 'ws', text: ' ' }, { type: 'str', text: '<arpa/inet.h>' }] },
    { num: 6, tokens: [{ type: 'ws', text: ' ' }] },
    { num: 7, tokens: [{ type: 'kw', text: '#define' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'PORT' }, { type: 'ws', text: ' ' }, { type: 'num', text: '8080' }] },
    { num: 8, tokens: [{ type: 'kw', text: '#define' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'BUFFER_SIZE' }, { type: 'ws', text: ' ' }, { type: 'num', text: '1024' }] },
    { num: 9, tokens: [{ type: 'ws', text: ' ' }] },
    { num: 10, tokens: [{ type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'fn', text: 'main' }, { type: 'punc', text: '()' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 11, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'server_fd' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'client_fd' }, { type: 'punc', text: ';' }] },
    { num: 12, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'struct' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'sockaddr_in' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'address' }, { type: 'punc', text: ';' }] },
    { num: 13, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'char' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'buffer' }, { type: 'punc', text: '[' }, { type: 'id', text: 'BUFFER_SIZE' }, { type: 'punc', text: ']' }, { type: 'punc', text: ';' }] },
    { num: 14, tokens: [{ type: 'ws', text: ' ' }] },
    { num: 15, tokens: [{ type: 'ws', text: '    ' }, { type: 'id', text: 'server_fd' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'fn', text: 'socket' }, { type: 'punc', text: '(' }, { type: 'id', text: 'AF_INET' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'SOCK_STREAM' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 16, tokens: [{ type: 'ws', text: '    ' }, { type: 'fn', text: 'memset' }, { type: 'punc', text: '(' }, { type: 'op', text: '&' }, { type: 'id', text: 'address' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'kw', text: 'sizeof' }, { type: 'punc', text: '(' }, { type: 'id', text: 'address' }, { type: 'punc', text: ')' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 17, tokens: [{ type: 'ws', text: '    ' }, { type: 'id', text: 'address' }, { type: 'punc', text: '.' }, { type: 'id', text: 'sin_family' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'AF_INET' }, { type: 'punc', text: ';' }] },
    { num: 18, tokens: [{ type: 'ws', text: '    ' }, { type: 'id', text: 'address' }, { type: 'punc', text: '.' }, { type: 'id', text: 'sin_addr' }, { type: 'punc', text: '.' }, { type: 'id', text: 's_addr' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'fn', text: 'htonl' }, { type: 'punc', text: '(' }, { type: 'id', text: 'INADDR_ANY' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 19, tokens: [{ type: 'ws', text: '    ' }, { type: 'id', text: 'address' }, { type: 'punc', text: '.' }, { type: 'id', text: 'sin_port' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'fn', text: 'htons' }, { type: 'punc', text: '(' }, { type: 'id', text: 'PORT' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 20, tokens: [{ type: 'ws', text: ' ' }] },
    { num: 21, tokens: [{ type: 'ws', text: '    ' }, { type: 'fn', text: 'bind' }, { type: 'punc', text: '(' }, { type: 'id', text: 'server_fd' }, { type: 'punc', text: ',' }, { type: 'punc', text: '(' }, { type: 'kw', text: 'struct' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'sockaddr' }, { type: 'op', text: '*' }, { type: 'punc', text: ')' }, { type: 'op', text: '&' }, { type: 'id', text: 'address' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'kw', text: 'sizeof' }, { type: 'punc', text: '(' }, { type: 'id', text: 'address' }, { type: 'punc', text: ')' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 22, tokens: [{ type: 'ws', text: '    ' }, { type: 'fn', text: 'listen' }, { type: 'punc', text: '(' }, { type: 'id', text: 'server_fd' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'num', text: '3' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 23, tokens: [{ type: 'ws', text: ' ' }] },
    { num: 24, tokens: [{ type: 'ws', text: '    ' }, { type: 'id', text: 'client_fd' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'fn', text: 'accept' }, { type: 'punc', text: '(' }, { type: 'id', text: 'server_fd' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'kw', text: 'NULL' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'kw', text: 'NULL' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 25, tokens: [{ type: 'ws', text: '    ' }, { type: 'fn', text: 'read' }, { type: 'punc', text: '(' }, { type: 'id', text: 'client_fd' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'buffer' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'kw', text: 'sizeof' }, { type: 'punc', text: '(' }, { type: 'id', text: 'buffer' }, { type: 'punc', text: ')' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 26, tokens: [{ type: 'ws', text: '    ' }, { type: 'fn', text: 'printf' }, { type: 'punc', text: '(' }, { type: 'str', text: '"Received: %s\\\\n"' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'buffer' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 27, tokens: [{ type: 'ws', text: '    ' }, { type: 'fn', text: 'write' }, { type: 'punc', text: '(' }, { type: 'id', text: 'client_fd' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'str', text: '"HTTP/1.1 200 OK\\\\r\\\\n\\\\r\\\\nHello!"' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'num', text: '24' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 28, tokens: [{ type: 'ws', text: '    ' }, { type: 'fn', text: 'close' }, { type: 'punc', text: '(' }, { type: 'id', text: 'client_fd' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 29, tokens: [{ type: 'ws', text: '    ' }, { type: 'fn', text: 'close' }, { type: 'punc', text: '(' }, { type: 'id', text: 'server_fd' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 30, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'return' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ';' }] },
    { num: 31, tokens: [{ type: 'punc', text: '}' }] }
  ],
  varConfig: [
    { key: 'server_fd', name: 'server_fd', type: 'int', addr: '0x7ffc00', glowColor: 'rgba(34,197,94,0.35)', accentCls: 'text-green-400', badgeCls: 'text-green-400 border-green-500/30 bg-green-500/12', appearStep: 1 },
    { key: 'address', name: 'address', type: 'struct sockaddr_in', addr: '0x7ffc04', glowColor: 'rgba(59,130,246,0.35)', accentCls: 'text-blue-400', badgeCls: 'text-blue-400 border-blue-500/30 bg-blue-500/12', appearStep: 3 },
    { key: 'client_fd', name: 'client_fd', type: 'int', addr: '0x7ffc20', glowColor: 'rgba(168,85,247,0.35)', accentCls: 'text-purple-400', badgeCls: 'text-purple-400 border-purple-500/30 bg-purple-500/12', appearStep: 6 },
    { key: 'buffer', name: 'buffer', type: 'char[1024]', addr: '0x7ffc24', glowColor: 'rgba(249,115,22,0.35)', accentCls: 'text-orange-400', badgeCls: 'text-orange-400 border-orange-500/30 bg-orange-500/12', appearStep: 8 }
  ],
  scenes: [
    { step: 0, line: -1, executedLines: [], vars: {}, highlightVar: null, isDanger: false, output: [], explanation: { icon: 'rocket', text: '点击播放，开始学习网络编程', color: 'blue', actor: null, detail: null }, prediction: null, misconception: null, actor: null, target: null, timing: null },
    { step: 1, line: 15, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], vars: { server_fd: 3 }, highlightVar: 'server_fd', isDanger: false, output: [], explanation: { icon: 'socket', text: 'socket(AF_INET, SOCK_STREAM) 创建 TCP 套接字', color: 'yellow', actor: 'CPU', detail: 'socket() 创建网络通信端点。AF_INET=IPv4，SOCK_STREAM=TCP。返回文件描述符（如 3），用于后续操作。' }, prediction: { question: 'SOCK_STREAM 代表什么协议？', options: ['UDP', 'TCP', 'ICMP'], answer: 1 }, misconception: null, actor: 'CPU', target: 'var:server_fd', timing: 'socket-create' },
    { step: 2, line: 16, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], vars: { server_fd: 3 }, highlightVar: null, isDanger: false, output: [], explanation: { icon: 'gear', text: 'memset 清零 address 结构体', color: 'purple', actor: 'CPU', detail: 'memset 将 sockaddr_in 结构体全部置零，确保没有垃圾值。这是良好的编程习惯。' }, prediction: null, misconception: null, actor: 'CPU', target: 'code', timing: 'init' },
    { step: 3, line: 17, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], vars: { server_fd: 3, address: { sin_family: 'AF_INET' } }, highlightVar: 'address', isDanger: false, output: [], explanation: { icon: 'bolt', text: '配置 address：sin_family=AF_INET', color: 'green', actor: 'CPU', detail: '设置地址族为 IPv4。后续还要设置 IP 地址和端口号。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:address', timing: 'config' },
    { step: 4, line: 18, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17], vars: { server_fd: 3, address: { sin_family: 'AF_INET', sin_addr: 'INADDR_ANY' } }, highlightVar: 'address', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'sin_addr.s_addr=htonl(INADDR_ANY)', color: 'green', actor: 'CPU', detail: 'INADDR_ANY=0.0.0.0，监听所有网卡。htonl 将主机字节序转为网络字节序（大端）。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:address', timing: 'config' },
    { step: 5, line: 19, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18], vars: { server_fd: 3, address: { sin_family: 'AF_INET', sin_addr: 'INADDR_ANY', sin_port: 8080 } }, highlightVar: 'address', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'sin_port=htons(PORT)，端口 8080', color: 'green', actor: 'CPU', detail: 'htons 将端口转为网络字节序。服务器监听 8080 端口。完整配置：0.0.0.0:8080。' }, prediction: { question: '为什么要用 htons 转换端口？', options: ['语法规则', '大小端转换', '加密'], answer: 1 }, misconception: { title: '网络字节序（大端）', text: '网络协议规定大端字节序，但 x86 是小端。htonl/htons 确保跨平台一致性。' }, actor: 'CPU', target: 'var:address', timing: 'config' },
    { step: 6, line: 21, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], vars: { server_fd: 3, address: { sin_family: 'AF_INET', sin_addr: 'INADDR_ANY', sin_port: 8080 } }, highlightVar: 'server_fd', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'bind 绑定套接字到地址', color: 'green', actor: 'CPU', detail: 'bind 将套接字与 IP:Port 绑定。之后操作系统会将发往该地址的数据包路由到此套接字。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:server_fd', timing: 'bind' },
    { step: 7, line: 22, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21], vars: { server_fd: 3 }, highlightVar: 'server_fd', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'listen(server_fd, 3) 开始监听', color: 'green', actor: 'CPU', detail: 'listen 使套接字进入被动监听模式。参数 3 是 backlog（等待连接队列的最大长度）。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:server_fd', timing: 'listen' },
    { step: 8, line: 24, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23], vars: { server_fd: 3, client_fd: 4 }, highlightVar: 'client_fd', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'accept 阻塞等待客户端连接', color: 'green', actor: 'CPU', detail: 'accept 阻塞直到有客户端连接。返回新的套接字描述符（如 4），专门用于与该客户端通信。原套接字继续监听。' }, prediction: { question: 'accept 返回的是什么？', options: ['布尔值', '新的套接字 FD', '客户端 IP'], answer: 1 }, misconception: null, actor: 'CPU', target: 'var:client_fd', timing: 'accept' },
    { step: 9, line: 25, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24], vars: { server_fd: 3, client_fd: 4, buffer: 'GET / HTTP/1.1...' }, highlightVar: 'buffer', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'read 从客户端读取数据', color: 'green', actor: 'CPU', detail: 'read 阻塞读取客户端发送的数据到 buffer。这是同步 I/O 模型。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:buffer', timing: 'read' },
    { step: 10, line: 26, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25], vars: { server_fd: 3, client_fd: 4, buffer: 'GET / HTTP/1.1...' }, highlightVar: null, isDanger: false, output: [{ type: 'success', text: 'Received: GET / HTTP/1.1...' }], explanation: { icon: 'terminal', text: 'printf 输出接收到的请求', color: 'green', actor: 'CPU', detail: '显示客户端发送的 HTTP 请求。实际应用中会解析请求并生成响应。' }, prediction: null, misconception: null, actor: 'CPU', target: 'stdout', timing: 'process' },
    { step: 11, line: 27, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26], vars: { server_fd: 3, client_fd: 4 }, highlightVar: null, isDanger: false, output: [{ type: 'success', text: 'Received: GET / HTTP/1.1...' }], explanation: { icon: 'bolt', text: 'write 发送 HTTP 响应', color: 'green', actor: 'CPU', detail: 'write 向客户端发送 HTTP 响应："200 OK" + "Hello!"。完整的 TCP 通信：握手→请求→响应→关闭。' }, prediction: null, misconception: null, actor: 'CPU', target: 'network', timing: 'write' },
    { step: 12, line: 28, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27], vars: { server_fd: 3, client_fd: 'closed' }, highlightVar: 'client_fd', isDanger: false, output: [{ type: 'success', text: 'Received: GET / HTTP/1.1...' }], explanation: { icon: 'check', text: 'close(client_fd) 关闭客户端连接', color: 'green', actor: 'CPU', detail: '关闭与客户端的连接，释放套接字资源。服务器套接字仍然监听新连接。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:client_fd', timing: 'cleanup' },
    { step: 13, line: 29, executedLines: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28], vars: { server_fd: 'closed' }, highlightVar: 'server_fd', isDanger: false, output: [{ type: 'success', text: 'Received: GET / HTTP/1.1...' }], explanation: { icon: 'check', text: 'close(server_fd) 关闭服务器', color: 'green', actor: 'CPU', detail: '关闭监听套接字，服务器停止运行。完整的 TCP 服务器流程：socket→bind→listen→accept→read/write→close。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:server_fd', timing: 'cleanup' }
  ],
  summary: {
    oneLiner: 'socket 创建套接字，bind 绑定地址，listen 监听，accept 接受连接，read/write 通信',
    pitfalls: [
      'socket 创建的是通信端点，需要 bind 后才能被客户端连接',
      'accept 返回新的套接字用于与特定客户端通信，原套接字继续监听',
      'htonl/htons 进行主机字节序到网络字节序（大端）的转换'
    ],
    transferQuestion: '为什么 accept 要返回新的套接字，而不是复用原来的套接字？',
    miniExercise: {
      bugCode: 'int fd = socket(AF_INET, SOCK_STREAM, 0);\\n// 直接 read(fd, ...) 没有 bind/listen/accept\\n// 这样对吗？',
      hint: '不对！服务器套接字必须先 bind→listen→accept 才能通信。客户端用 connect 直接连接服务器。'
    }
  }
};
