window.LESSON_DATA = {
  meta: {
    id: 'l1-loop',
    title: '循环',
    chapter: 'level1',
    index: 4,
    filename: 'loop-timeout.c',
    keyPoints: ['for 循环', 'while 循环', '超时处理']
  },
  codeLines: [
    { num: 1, tokens: [{ type: 'pp', text: '#include' }, { type: 'ws', text: ' ' }, { type: 'str', text: '<stdio.h>' }] },
    { num: 2, tokens: [{ type: 'pp', text: '#include' }, { type: 'ws', text: ' ' }, { type: 'str', text: '<stdint.h>' }] },
    { num: 3, tokens: [{ type: 'ws', text: ' ' }] },
    { num: 4, tokens: [{ type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'fn', text: 'main' }, { type: 'punc', text: '()' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 5, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'sum' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ';' }] },
    { num: 6, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'for' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '(' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ';' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' }, { type: 'ws', text: ' ' }, { type: 'op', text: '<' }, { type: 'ws', text: ' ' }, { type: 'num', text: '5' }, { type: 'punc', text: ';' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' }, { type: 'op', text: '++' }, { type: 'punc', text: ')' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 7, tokens: [{ type: 'ws', text: '        ' }, { type: 'id', text: 'sum' }, { type: 'ws', text: ' ' }, { type: 'op', text: '+=' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'i' }, { type: 'punc', text: ';' }] },
    { num: 8, tokens: [{ type: 'ws', text: '    ' }, { type: 'punc', text: '}' }] },
    { num: 9, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'uint32_t' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'timeout' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'num', text: '1000' }, { type: 'punc', text: ';' }] },
    { num: 10, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'int' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'ready' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ';' }, { type: 'ws', text: ' ' }, { type: 'cmt', text: '// 0=未就绪' }] },
    { num: 11, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'while' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '(' }, { type: 'id', text: 'timeout' }, { type: 'ws', text: ' ' }, { type: 'op', text: '>' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'ws', text: ' ' }, { type: 'op', text: '&&' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'ready' }, { type: 'ws', text: ' ' }, { type: 'op', text: '==' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ')' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 12, tokens: [{ type: 'ws', text: '        ' }, { type: 'id', text: 'timeout' }, { type: 'op', text: '--' }, { type: 'punc', text: ';' }, { type: 'ws', text: ' ' }, { type: 'cmt', text: '// 倒计时' }] },
    { num: 13, tokens: [{ type: 'ws', text: '        ' }, { type: 'kw', text: 'if' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '(' }, { type: 'id', text: 'timeout' }, { type: 'ws', text: ' ' }, { type: 'op', text: '==' }, { type: 'ws', text: ' ' }, { type: 'num', text: '500' }, { type: 'punc', text: ')' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 14, tokens: [{ type: 'ws', text: '            ' }, { type: 'id', text: 'ready' }, { type: 'ws', text: ' ' }, { type: 'op', text: '=' }, { type: 'ws', text: ' ' }, { type: 'num', text: '1' }, { type: 'punc', text: ';' }, { type: 'ws', text: ' ' }, { type: 'cmt', text: '// 模拟就绪' }] },
    { num: 15, tokens: [{ type: 'ws', text: '        ' }, { type: 'punc', text: '}' }] },
    { num: 16, tokens: [{ type: 'ws', text: '    ' }, { type: 'punc', text: '}' }] },
    { num: 17, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'if' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '(' }, { type: 'id', text: 'timeout' }, { type: 'ws', text: ' ' }, { type: 'op', text: '==' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ')' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 18, tokens: [{ type: 'ws', text: '        ' }, { type: 'fn', text: 'printf' }, { type: 'punc', text: '(' }, { type: 'str', text: '"[TIMEOUT] Operation timed out!\\n"' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 19, tokens: [{ type: 'ws', text: '    ' }, { type: 'punc', text: '}' }, { type: 'ws', text: ' ' }, { type: 'kw', text: 'else' }, { type: 'ws', text: ' ' }, { type: 'punc', text: '{' }] },
    { num: 20, tokens: [{ type: 'ws', text: '        ' }, { type: 'fn', text: 'printf' }, { type: 'punc', text: '(' }, { type: 'str', text: '"[OK] Ready after %d ms\\n"' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'num', text: '1000' }, { type: 'op', text: '-' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'timeout' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 21, tokens: [{ type: 'ws', text: '    ' }, { type: 'punc', text: '}' }] },
    { num: 22, tokens: [{ type: 'ws', text: '    ' }, { type: 'fn', text: 'printf' }, { type: 'punc', text: '(' }, { type: 'str', text: '"sum = %d\\n"' }, { type: 'punc', text: ',' }, { type: 'ws', text: ' ' }, { type: 'id', text: 'sum' }, { type: 'punc', text: ')' }, { type: 'punc', text: ';' }] },
    { num: 23, tokens: [{ type: 'ws', text: '    ' }, { type: 'kw', text: 'return' }, { type: 'ws', text: ' ' }, { type: 'num', text: '0' }, { type: 'punc', text: ';' }] },
    { num: 24, tokens: [{ type: 'punc', text: '}' }] }
  ],
  varConfig: [
    { key: 'sum', name: 'sum', type: 'int', addr: '0x7ffc00', glowColor: 'rgba(34,197,94,0.35)', accentCls: 'text-green-400', badgeCls: 'text-green-400 border-green-500/30 bg-green-500/12', appearStep: 1 },
    { key: 'i', name: 'i', type: 'int', addr: '0x7ffc04', glowColor: 'rgba(168,85,247,0.35)', accentCls: 'text-purple-400', badgeCls: 'text-purple-400 border-purple-500/30 bg-purple-500/12', appearStep: 2 },
    { key: 'timeout', name: 'timeout', type: 'uint32_t', addr: '0x7ffc08', glowColor: 'rgba(59,130,246,0.35)', accentCls: 'text-blue-400', badgeCls: 'text-blue-400 border-blue-500/30 bg-blue-500/12', appearStep: 5 },
    { key: 'ready', name: 'ready', type: 'int', addr: '0x7ffc0c', glowColor: 'rgba(249,115,22,0.35)', accentCls: 'text-orange-400', badgeCls: 'text-orange-400 border-orange-500/30 bg-orange-500/12', appearStep: 6 }
  ],
  scenes: [
    { step: 0, line: -1, executedLines: [], vars: {}, highlightVar: null, isDanger: false, output: [], explanation: { icon: 'rocket', text: '点击播放，开始学习循环', color: 'blue', actor: null, detail: null }, prediction: null, misconception: null, actor: null, target: null, timing: null },
    { step: 1, line: 5, executedLines: [3, 4], vars: { sum: 0 }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'memory', text: '声明 sum = 0，累加器', color: 'yellow', actor: 'CPU', detail: 'sum 初始化为 0，用于 for 循环累加。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:sum', timing: 'main-loop' },
    { step: 2, line: 6, executedLines: [3, 4, 5], vars: { sum: 0, i: 0 }, highlightVar: 'i', isDanger: false, output: [], explanation: { icon: 'memory', text: 'for 循环初始化 i=0', color: 'blue', actor: 'CPU', detail: 'for 循环三要素：初始化 (i=0)、条件 (i<5)、迭代 (i++)。' }, prediction: { question: 'for 循环执行几次？', options: ['4 次 (0-3)', '5 次 (0-4)', '6 次 (0-5)'], answer: 1 }, misconception: null, actor: 'CPU', target: 'var:i', timing: 'loop-init' },
    { step: 3, line: 7, executedLines: [3, 4, 5, 6], vars: { sum: 0, i: 0 }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'bolt', text: '第一次循环：sum += 0，sum 仍为 0', color: 'green', actor: 'CPU', detail: 'i=0 时，sum = 0 + 0 = 0。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:sum', timing: 'loop-body' },
    { step: 4, line: 6, executedLines: [3, 4, 5, 6, 7], vars: { sum: 0, i: 1 }, highlightVar: 'i', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'i++ 后 i=1，继续循环', color: 'purple', actor: 'CPU', detail: 'i 自增为 1，判断 1<5 为真。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:i', timing: 'loop-iter' },
    { step: 5, line: 7, executedLines: [3, 4, 5, 6, 7, 6], vars: { sum: 1, i: 1 }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'bolt', text: '第二次循环：sum += 1，sum 变为 1', color: 'green', actor: 'CPU', detail: 'sum = 0 + 1 = 1。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:sum', timing: 'loop-body' },
    { step: 6, line: 6, executedLines: [3, 4, 5, 6, 7, 6, 7], vars: { sum: 1, i: 2 }, highlightVar: 'i', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'i++ 后 i=2，继续循环', color: 'purple', actor: 'CPU', detail: 'i 自增为 2，判断 2<5 为真。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:i', timing: 'loop-iter' },
    { step: 7, line: 7, executedLines: [3, 4, 5, 6, 7, 6, 7, 6], vars: { sum: 3, i: 2 }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'bolt', text: '第三次循环：sum += 2，sum 变为 3', color: 'green', actor: 'CPU', detail: 'sum = 1 + 2 = 3。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:sum', timing: 'loop-body' },
    { step: 8, line: 6, executedLines: [3, 4, 5, 6, 7, 6, 7, 6, 7], vars: { sum: 3, i: 3 }, highlightVar: 'i', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'i++ 后 i=3，继续循环', color: 'purple', actor: 'CPU', detail: 'i 自增为 3，判断 3<5 为真。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:i', timing: 'loop-iter' },
    { step: 9, line: 7, executedLines: [3, 4, 5, 6, 7, 6, 7, 6, 7, 6], vars: { sum: 6, i: 3 }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'bolt', text: '第四次循环：sum += 3，sum 变为 6', color: 'green', actor: 'CPU', detail: 'sum = 3 + 3 = 6。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:sum', timing: 'loop-body' },
    { step: 10, line: 6, executedLines: [3, 4, 5, 6, 7, 6, 7, 6, 7, 6, 7], vars: { sum: 6, i: 4 }, highlightVar: 'i', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'i++ 后 i=4，继续循环', color: 'purple', actor: 'CPU', detail: 'i 自增为 4，判断 4<5 为真，最后一次。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:i', timing: 'loop-iter' },
    { step: 11, line: 7, executedLines: [3, 4, 5, 6, 7, 6, 7, 6, 7, 6, 7, 6], vars: { sum: 10, i: 4 }, highlightVar: 'sum', isDanger: false, output: [], explanation: { icon: 'bolt', text: '第五次循环：sum += 4，sum 变为 10', color: 'green', actor: 'CPU', detail: 'sum = 6 + 4 = 10。0+1+2+3+4=10。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:sum', timing: 'loop-body' },
    { step: 12, line: 8, executedLines: [3, 4, 5, 6, 7, 6, 7, 6, 7, 6, 7, 6, 7], vars: { sum: 10, i: 4 }, highlightVar: null, isDanger: false, output: [], explanation: { icon: 'check', text: 'i++ 后 i=5，判断 i<5 为假，退出循环', color: 'green', actor: 'CPU', detail: '循环结束。sum=10。' }, prediction: null, misconception: null, actor: 'CPU', target: 'control-flow', timing: 'loop-exit' },
    { step: 13, line: 9, executedLines: [3, 4, 5, 6, 7, 6, 7, 6, 7, 6, 7, 6, 7, 8], vars: { sum: 10, timeout: 1000 }, highlightVar: 'timeout', isDanger: false, output: [], explanation: { icon: 'memory', text: '声明 uint32_t 变量 timeout = 1000，超时计数器', color: 'blue', actor: 'CPU', detail: 'timeout 用于 while 循环超时控制。嵌入式中常用这种模式等待硬件事件，防止无限等待。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:timeout', timing: 'main-loop' },
    { step: 14, line: 10, executedLines: [3, 4, 5, 6, 7, 6, 7, 6, 7, 6, 7, 6, 7, 8, 9], vars: { sum: 10, timeout: 1000, ready: 0 }, highlightVar: 'ready', isDanger: false, output: [], explanation: { icon: 'memory', text: '声明 int 变量 ready = 0，表示未就绪', color: 'orange', actor: 'CPU', detail: 'ready 标志位模拟硬件事件。0=未就绪，1=就绪。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:ready', timing: 'main-loop' },
    { step: 15, line: 11, executedLines: [3, 4, 5, 6, 7, 6, 7, 6, 7, 6, 7, 6, 7, 8, 9, 10], vars: { sum: 10, timeout: 1000, ready: 0 }, highlightVar: null, isDanger: false, output: [], explanation: { icon: 'target', text: 'while 判断 timeout>0 && ready==0，条件为真', color: 'orange', actor: 'CPU', detail: '&& 是逻辑与，两边都为真结果才为真。1000>0 为真，ready==0 为真，所以进入循环。这是典型的"等待直到超时或事件发生"模式。' }, prediction: { question: 'while 循环何时退出？', options: ['timeout=0 时', 'ready=1 时', '任一条件满足时'], answer: 2 }, misconception: null, actor: 'CPU', target: 'control-flow', timing: 'loop-check' },
    { step: 16, line: 12, executedLines: [3, 4, 5, 6, 7, 6, 7, 6, 7, 6, 7, 6, 7, 8, 9, 10, 11], vars: { sum: 10, timeout: 999, ready: 0 }, highlightVar: 'timeout', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'timeout-- 倒计时 999', color: 'green', actor: 'CPU', detail: '每次循环 timeout 减 1，模拟时间流逝。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:timeout', timing: 'loop-body' },
    { step: 17, line: 13, executedLines: [3, 4, 5, 6, 7, 6, 7, 6, 7, 6, 7, 6, 7, 8, 9, 10, 11, 12], vars: { sum: 10, timeout: 999, ready: 0 }, highlightVar: null, isDanger: false, output: [], explanation: { icon: 'target', text: '判断 timeout==500，即 999==500 为假', color: 'orange', actor: 'CPU', detail: 'timeout 还没到 500，不执行就绪模拟。' }, prediction: null, misconception: null, actor: 'CPU', target: 'control-flow', timing: 'condition-check' },
    { step: 18, line: 11, executedLines: [3, 4, 5, 6, 7, 6, 7, 6, 7, 6, 7, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], vars: { sum: 10, timeout: 999, ready: 0 }, highlightVar: null, isDanger: false, output: [], explanation: { icon: 'target', text: '回到 while 开始，继续循环', color: 'orange', actor: 'CPU', detail: '为加快演示，我们快进到 timeout=500 的时刻。' }, prediction: null, misconception: null, actor: 'CPU', target: 'control-flow', timing: 'loop-iter' },
    { step: 19, line: 11, executedLines: [3, 4, 5, 6, 7, 6, 7, 6, 7, 6, 7, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15], vars: { sum: 10, timeout: 500, ready: 0 }, highlightVar: null, isDanger: false, output: [], explanation: { icon: 'target', text: 'while 判断，timeout=500>0 且 ready=0，继续循环', color: 'orange', actor: 'CPU', detail: '经过 500 次循环，timeout 从 1000 减到 500。' }, prediction: null, misconception: null, actor: 'CPU', target: 'control-flow', timing: 'loop-check' },
    { step: 20, line: 12, executedLines: [3, 4, 5, 6, 7, 6, 7, 6, 7, 6, 7, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 11], vars: { sum: 10, timeout: 499, ready: 0 }, highlightVar: 'timeout', isDanger: false, output: [], explanation: { icon: 'bolt', text: 'timeout-- 变为 499', color: 'green', actor: 'CPU', detail: '继续倒计时。' }, prediction: null, misconception: null, actor: 'CPU', target: 'var:timeout', timing: 'loop-body' },
    { step: 21, line: 13, executedLines: [3, 4, 5, 6, 7, 6, 7, 6, 7, 6, 7, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 11, 12], vars: { sum: 10, timeout: 499, ready: 0 }, highlightVar: null, isDanger: false, output: [], explanation: { icon: 'target', text: '判断 timeout==500，即 499==500 为假', color: 'orange', actor: 'CPU', detail: '这里有个逻辑问题：timeout 从 500 减到 499 后才判断，所以永远不会匹配 500。代码有 bug！应该是先判断再减，或者判断 499。' }, prediction: null, misconception: null, actor: 'CPU', target: 'control-flow', timing: 'condition-check' },
    { step: 22, line: 11, executedLines: [3, 4, 5, 6, 7, 6, 7, 6, 7, 6, 7, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15], vars: { sum: 10, timeout: 499, ready: 0 }, highlightVar: null, isDanger: false, output: [], explanation: { icon: 'target', text: '继续循环直到 timeout=0', color: 'orange', actor: 'CPU', detail: '由于判断条件永远不满足，ready 始终为 0，循环会持续到 timeout=0。' }, prediction: null, misconception: null, actor: 'CPU', target: 'control-flow', timing: 'loop-iter' },
    { step: 23, line: 17, executedLines: [3, 4, 5, 6, 7, 6, 7, 6, 7, 6, 7, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 16], vars: { sum: 10, timeout: 0, ready: 0 }, highlightVar: 'timeout', isDanger: true, output: [], explanation: { icon: 'alert', text: 'timeout=0，退出 while 循环', color: 'red', actor: 'CPU', detail: 'timeout 减到 0，while 条件 timeout>0 为假，退出循环。超时发生！' }, prediction: null, misconception: null, actor: 'CPU', target: 'control-flow', timing: 'loop-exit' },
    { step: 24, line: 18, executedLines: [3, 4, 5, 6, 7, 6, 7, 6, 7, 6, 7, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 16, 17], vars: { sum: 10, timeout: 0, ready: 0 }, highlightVar: null, isDanger: false, output: [{ type: 'success', text: '[TIMEOUT] Operation timed out!' }], explanation: { icon: 'terminal', text: 'timeout==0 为真，输出超时错误', color: 'green', actor: 'CPU', detail: '超时处理是嵌入式系统的关键技术。没有超时保护，系统可能永久等待硬件事件导致死锁。' }, prediction: null, misconception: null, actor: 'CPU', target: 'stdout', timing: 'main-loop' },
    { step: 25, line: 22, executedLines: [3, 4, 5, 6, 7, 6, 7, 6, 7, 6, 7, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21], vars: { sum: 10, timeout: 0, ready: 0 }, highlightVar: null, isDanger: false, output: [{ type: 'success', text: '[TIMEOUT] Operation timed out!' }, { type: 'success', text: 'sum = 10' }], explanation: { icon: 'terminal', text: '输出 sum = 10', color: 'green', actor: 'CPU', detail: 'for 循环的累加结果是正确的 10。' }, prediction: null, misconception: null, actor: 'CPU', target: 'stdout', timing: 'main-loop' }
  ],
  summary: {
    oneLiner: 'for 适合已知次数循环，while 适合条件控制，超时保护防止无限等待',
    pitfalls: [
      'while 循环条件判断顺序很重要，先减后判可能错过目标值',
      '超时保护是嵌入式必备技术，防止硬件事件永不发生导致死锁',
      'for 循环 i<5 执行 5 次，i<=5 会执行 6 次导致越界'
    ],
    transferQuestion: '如果要让 ready 在 timeout=500 时触发，应该如何修改代码？',
    miniExercise: {
      bugCode: 'while (ready == 0) {\n    // 等待就绪\n}\n// 这个循环有什么问题？',
      hint: '没有超时保护，如果 ready 永远不变为 1，会无限循环'
    }
  }
};
